--- #YAML:1.0
name: Win32-Sound
abstract: An extension to play with Windows sounds
version: 0.52
author:
  - Aldo Calpini <dada@perl.it>
  - Jan Dubois <jand@activestate.com>
license: perl
requires: 
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
  homepage: https://github.com/dada/win32-sound
  repository: https://github.com/dada/win32-sound
meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Jan Dubois
